### ISSUE TITLE
Add hbase.zookeeper.property.clientPort setting

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/hbase-operator#355]
We don't know why but while investigating another issue @sbernauer and I found that HBase was using the wrong port to connect to ZK despite the connection string looking good.

It might therefore be a good idea to just set the `hbase.zookeeper.property.clientPort` setting just to be safe:

```xml
  <property>
    <name>hbase.zookeeper.property.clientPort</name>
    <value>2282</value>
  </property>
```

The value needs to be read from ZK config

**Comment by sbernauer** [comment]
Related to https://github.com/stackabletech/hbase-operator/issues/354, might makes sense to implement together

**Comment by maltesander** [comment]
What port is it connecting to? 2181? This should ideally be extracted from the discovery config map?
Currently 2181 and 2282 work because of the port unification if TLS is used anywhere (https://github.com/stackabletech/zookeeper-operator/issues/480).

**Comment by sbernauer** [comment]
We have a spike up and running, will raise PRs today @maltesander :)

**Comment by sbernauer** [comment]
And yeah, we need to expose the port to use in the znode discovery cm

**Comment by sbernauer** [comment]
Jus for the record some logs here
```  <!-- New, resolved the problem -->
  <property>                                                                                                                                                                                                                                
    <name>hbase.zookeeper.property.clientPort</name>                                                                                                                                                                                        
    <value>2282</value>                                                                                                                                                                                                                     
  </property>                                                                                                                                                                                                                               
  <property>                                                                                                                                                                                                                                
    <name>hbase.zookeeper.quorum</name>                                                                                                                                                                                                     
    <value>test-zk-server-default-0.test-zk-server-default.kuttl-test-known-duck.svc.cluster.local:2282/znode-636de0b5-d08d-4c8a-afcb-a68623b3b6d4</value>                                                                                  
  </p
```

```2023-04-28T08:06:17,269 INFO  [ReadOnlyZKClient-test-zk-server-default-0.test-zk-server-default.kuttl-test-sound-bulldog.svc.cluster.local:2181@0x7ee7dcaf-SendThread(test-zk-server-default-0.test-zk-server-default.kuttl-test-sound-bulldog.svc.cluster.local:2181)] zookeeper.ClientCnxn: Socket error occurred: test-zk-server-default-0.test-zk-server-default.kuttl-test-sound-bulldog.svc.cluster.local/10.244.0.89:2181: Connection refused
2023-04-28T08:06:17,269 DEBUG [ReadOnlyZKClient-test-zk-server-default-0.test-zk-server-default.kuttl-test-sound-bulldog.svc.cluster.local:2181@0x7ee7dcaf-SendThread(test-zk-server-default-0.test-zk-server-default.kuttl-test-sound-bulldog.svc.cluster.local:2181)] zookeeper.ClientCnxnSocketNIO: Ignoring exception during shutdown input
java.nio.channels.ClosedChannelException: null
        at sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:160) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.shutdownInput(SocketChannelImpl.java:913) ~[?:?]
        at sun.nio.ch.SocketAdaptor.shutdownInput(SocketAdaptor.java:398) ~[?:?]
        at org.apache.zookeeper.ClientCnxnSocketNIO.cleanup(ClientCnxnSocketNIO.java:198) ~[zookeeper-3.5.7.jar:3.5.7]
        at org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1338) ~[zookeeper-3.5.7.jar:3.5.7]
        at org.apache.zookeeper.ClientCnxn$SendThread.cleanAndNotifyState(ClientCnxn.java:1276) ~[zookeeper-3.5.7.jar:3.5.7]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1254) ~[zookeeper-3.5.7.jar:3.5.7]
2023-04-28T08:06:17,269 DEBUG [ReadOnlyZKClient-test-zk-server-default-0.test-zk-server-default.kuttl-test-sound-bulldog.svc.cluster.local:2181@0x7ee7dcaf-SendThread(test-zk-server-default-0.test-zk-server-default.kuttl-test-sound-bulldog.svc.cluster.local:2181)] zookeeper.ClientCnxnSocketNIO: Ignoring exception during shutdown output
java.nio.channels.ClosedChannelException: null
        at sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:160) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.shutdownOutput(SocketChannelImpl.java:930) ~[?:?]
        at sun.nio.ch.SocketAdaptor.shutdownOutput(SocketAdaptor.java:406) ~[?:?]
        at org.apache.zookeeper.ClientCnxnSocketNIO.cleanup(ClientCnxnSocketNIO.java:205) ~[zookeeper-3.5.7.jar:3.5.7]
        at org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1338) ~[zookeeper-3.5.7.jar:3.5.7]
        at org.apache.zookeeper.ClientCnxn$SendThread.cleanAndNotifyState(ClientCnxn.java:1276) ~[zookeeper-3.5.7.jar:3.5.7]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1254) ~[zookeeper-3.5.7.jar:3.5.7]```

**Comment by lfrancke** [comment]
This can be closed, right?

**Comment by sbernauer** [comment]
Yes
